### ISSUE TITLE
Unable to to use by.React()

### ISSUE THREAD

**Issue by PrasKams** [abhinaba1080/protractor-react-selector#11]
Hello @abhinaba-ghosh 
Followed all steps to enable and make use of `by.React()` but its just not doing anything, not throwing error either. But if i make it await, then its throwing function timed-out.
Snippet from my conf.js
`const protractorPlugins = [{package: 'protractor-react-selector'}];`

**Element getter from my PO- use of by.React()**
```
static get businessName(){
        return element(by.react('e', {name: "name"}));
    }
 static get primaryContactName(){
        return element(by.react('e', {name: "primaryContactName"}));
    }
```
**Calling element to work on the actions**
```
await this.primaryContactName.sendKeys(data.createAccount.primaryContactName + this.getCurrentDateString());
await this.businessName.sendKeys(data.createAccount.businessName+ timeStampString);
```

Please let me know where am i going wrong??

**Comment by abhinaba-ghosh** [comment]
Hi @PrasKams , thanks for raising the issue. May I know whether you are calling ```waitForReact()``` before using ```by.react``` selector?

basic usage :

```js
await browser.waitForReact(timeout, reactRoot)
```

**Comment by PrasKams** [comment]
this is how am calling waitForReact()
```
static async isReady() {
        debugger;
        browser.waitForReact();
        return eleHelpers.awaitVisibility(this.paginationText, "page cannot be loaded in time", 7000);
      }
```
in a totally different function where am checking page is ready, or is it not the right way to call?? am not awaiting that sentence as well, i guess it is only working because i have debugger there :)

**Comment by abhinaba-ghosh** [comment]
Hi @PrasKams , you need to use ```await``` as it is an asynchronous process. Also, you need to pass the react root selector if you have different react roots other than ```#root```. You may also want to pass the timeout value if the root takes more than ```10000 ms ``` to load in the DOM. 

If you already have taken these steps, then your ```by.react``` selector should work fine. Would you mind creating a sample git repository so that I can reproduce the issue and work on the same? 

Thanks. 

You can always ping me [here](https://www.linkedin.com/in/abhinaba-ghosh-9a2ab8a0/) for any private repository.

**Comment by PrasKams** [comment]
Hey @abhinaba-ghosh,
thx for your inputs, i will make those suggested changes and get back to you. as far as creating sample repo, it will take time, not sure about it, but will revert if i face further challenges

**Comment by abhinaba-ghosh** [comment]
Thanks. Please re-open the issue, if you find the bug re-occurring.
